-- ============================================================================
-- Living Plant Asset & Nursery Stock Management System — PostgreSQL install
-- (Supabase-compatible)
--
-- Ported from docs/install.sql (MySQL/MariaDB) for a Supabase Postgres
-- deployment. Structural port, table for table — see "Conversion notes"
-- below for every place the two engines disagree and what was chosen here.
--
-- Seeded with the ACTUAL data running in production as of 2026-09-23, not
-- the older demo dataset described in install.sql's own header comment —
-- that file's `trees` seed rows were never actually present in it despite
-- the comment claiming 103 rows, so this file reflects ground truth
-- (a mysqldump of the live database), not that stale description.
--
-- Run:
--   psql "$DATABASE_URL" -f docs/install.postgres.sql
-- (DATABASE_URL is the connection string from Supabase's project settings —
-- Supabase already gives you a database, so unlike install.sql there is no
-- CREATE DATABASE/USE step here; everything goes into the "public" schema.)
--
-- Conversion notes (MySQL -> PostgreSQL):
--   - BIGINT/INT UNSIGNED AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--     (Postgres has no UNSIGNED; ids are always positive by construction,
--     so no CHECK was added for that)
--   - ENUM(...) -> VARCHAR + CHECK constraint, not a native Postgres ENUM
--     type. Values are always read/written as plain strings via PDO on the
--     PHP side either way, so this is a behavior-preserving choice that
--     avoids the extra ceremony of CREATE TYPE ... AS ENUM and ALTER TYPE
--     the day a value needs to be added.
--   - TINYINT(1) -> SMALLINT (NOT BOOLEAN). This is the one conversion
--     that would have silently broken PHP if done the "obvious" way:
--     PDO's pgsql driver returns a native BOOLEAN column as the strings
--     't'/'f', not '1'/'0' — every existing `== 1` / `(bool) $row[...]`
--     comparison in the PHP code (written against MySQL's TINYINT(1),
--     which PDO returns as '1'/'0') would misbehave against 't'/'f'
--     (`(bool) 'f'` is TRUE in PHP). SMALLINT 0/1 round-trips through PDO
--     exactly like MySQL's TINYINT(1) did, so no PHP changes were needed.
--   - DATETIME -> TIMESTAMP; DEFAULT CURRENT_TIMESTAMP -> DEFAULT now()
--   - `... ON UPDATE CURRENT_TIMESTAMP` has no Postgres equivalent —
--     replaced with a BEFORE UPDATE trigger per table (set_updated_at(),
--     or set_last_seen_at() for the one column that isn't named
--     updated_at: visitors.last_seen_at)
--   - Inline `INDEX name (col)` inside CREATE TABLE isn't valid Postgres —
--     pulled out into standalone CREATE INDEX statements after the table
--   - Inline `UNIQUE KEY name (col)` -> `CONSTRAINT name UNIQUE (col)`,
--     still inline (Postgres supports this form directly)
--   - `JSON` columns (audit_logs.before_json/after_json) -> TEXT, not
--     JSONB — audit_logs is write-only from PHP (json_encode() then
--     stored), nothing in the codebase queries into the JSON with SQL
--     operators, so TEXT avoids any implicit-cast surprises for zero
--     functional difference to the app
--   - Backtick identifier quoting in seed INSERTs -> removed entirely
--     (every table/column name here is lowercase snake_case with no
--     Postgres reserved-word collisions, so no quoting is needed at all)
--   - `ENGINE=InnoDB`, `CHARACTER SET utf8mb4 COLLATE ...` -> dropped
--     (Postgres/Supabase databases are UTF8 by default)
-- ============================================================================

-- ---------------------------------------------------------------
-- Reusable trigger functions standing in for MySQL's
-- `... ON UPDATE CURRENT_TIMESTAMP` (see conversion notes above).
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_last_seen_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.last_seen_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------
-- Roles & Permissions (RBAC) — see docs/rbac.md for the full design.
-- ---------------------------------------------------------------
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_key    VARCHAR(40) NOT NULL UNIQUE,
    name_th     VARCHAR(100) NOT NULL,
    name_en     VARCHAR(100) NOT NULL,
    description TEXT NULL,
    is_system   SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE permissions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_key VARCHAR(60) NOT NULL UNIQUE,
    module         VARCHAR(40) NOT NULL,
    description    TEXT NULL
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- ---------------------------------------------------------------
-- Admins (separate from visitor identity system entirely)
-- ---------------------------------------------------------------
CREATE TABLE admins (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username               VARCHAR(100) NOT NULL UNIQUE,
    password_hash          VARCHAR(255) NOT NULL,
    role_id                BIGINT NOT NULL REFERENCES roles(id),
    failed_login_attempts  INTEGER NOT NULL DEFAULT 0,
    locked_until           TIMESTAMP NULL,
    created_at             TIMESTAMP NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------
-- Global admin-configurable settings (e.g. default map banner/url)
-- ---------------------------------------------------------------
CREATE TABLE settings (
    setting_key   VARCHAR(100) PRIMARY KEY,
    setting_value TEXT NULL,
    updated_at    TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Categories
-- ---------------------------------------------------------------
CREATE TABLE categories (
    code       CHAR(3) PRIMARY KEY,
    name_th    VARCHAR(100) NOT NULL,
    name_en    VARCHAR(100) NULL,
    name_zh    VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------
-- Subtypes ("ชนิด")
-- ---------------------------------------------------------------
CREATE TABLE subtypes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code CHAR(3) NULL REFERENCES categories(code),
    name_th       VARCHAR(100) NOT NULL,
    name_en       VARCHAR(100) NULL,
    name_zh       VARCHAR(100) NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------
-- Zones — physical areas.
-- ---------------------------------------------------------------
CREATE TABLE zones (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_code    VARCHAR(50) NOT NULL UNIQUE,
    zone_number  CHAR(3) NOT NULL UNIQUE,
    name         VARCHAR(150) NOT NULL,
    name_en      VARCHAR(150) NULL,
    name_zh      VARCHAR(150) NULL,
    description    TEXT NULL,
    description_en TEXT NULL,
    description_zh TEXT NULL,
    map_pin_x    DECIMAL(5,2) NULL,
    map_pin_y    DECIMAL(5,2) NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_zones_updated_at BEFORE UPDATE ON zones
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Species — master data shared by every individual plant of that species.
-- ---------------------------------------------------------------
CREATE TABLE species (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code      CHAR(3) NOT NULL REFERENCES categories(code),
    subtype_id         BIGINT NULL REFERENCES subtypes(id),
    species_code       CHAR(3) NOT NULL,
    classification_id  CHAR(10) NULL UNIQUE,
    name               VARCHAR(150) NOT NULL,
    name_en            VARCHAR(150) NULL,
    name_zh            VARCHAR(150) NULL,
    name_common        VARCHAR(150) NULL,
    name_scientific    VARCHAR(150) NULL,
    image_path         VARCHAR(255) NULL,
    description        TEXT NULL,
    description_en     TEXT NULL,
    description_zh     TEXT NULL,
    care_instructions    TEXT NULL,
    care_instructions_en TEXT NULL,
    care_instructions_zh TEXT NULL,
    characteristics     TEXT NULL,
    characteristics_en  TEXT NULL,
    characteristics_zh  TEXT NULL,
    properties          TEXT NULL,
    properties_en       TEXT NULL,
    properties_zh       TEXT NULL,
    benefits            TEXT NULL,
    benefits_en         TEXT NULL,
    benefits_zh         TEXT NULL,
    cautions            TEXT NULL,
    cautions_en         TEXT NULL,
    cautions_zh         TEXT NULL,
    part_uses           TEXT NULL,
    part_uses_en        TEXT NULL,
    part_uses_zh        TEXT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_species_category_species UNIQUE (category_code, species_code)
);
CREATE TRIGGER trg_species_updated_at BEFORE UPDATE ON species
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Extra subtypes for a species belonging to more than one "ชนิด"
-- ---------------------------------------------------------------
CREATE TABLE species_subtypes (
    species_id BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    subtype_id BIGINT NOT NULL REFERENCES subtypes(id) ON DELETE CASCADE,
    PRIMARY KEY (species_id, subtype_id)
);

-- ---------------------------------------------------------------
-- Trees — individual plant specimens ("Plant Asset" / "Tree ID").
-- ---------------------------------------------------------------
CREATE TABLE trees (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug               VARCHAR(150) NULL UNIQUE,
    species_id         BIGINT NOT NULL REFERENCES species(id),
    zone_id            BIGINT NOT NULL REFERENCES zones(id),
    area_code          CHAR(2) NOT NULL DEFAULT '01',
    plant_code             CHAR(15) NULL UNIQUE,
    plant_code_updated_at  TIMESTAMP NULL,
    label              VARCHAR(150) NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'healthy'
        CHECK (status IN ('healthy','needs_attention','removed')),
    data_status        VARCHAR(20) NOT NULL DEFAULT 'published'
        CHECK (data_status IN ('draft','verified','published')),
    image_path         VARCHAR(255) NULL,
    map_image_path     VARCHAR(255) NULL,
    map_url            VARCHAR(255) NULL,
    qr_code_path       VARCHAR(255) NULL,
    latitude            DECIMAL(10,7) NULL,
    longitude           DECIMAL(10,7) NULL,
    location_updated_at TIMESTAMP NULL,
    map_pin_x          DECIMAL(5,2) NULL,
    map_pin_y          DECIMAL(5,2) NULL,
    display_order      INTEGER NOT NULL,
    is_active          SMALLINT NOT NULL DEFAULT 1,
    created_at         TIMESTAMP NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_trees_display_order UNIQUE (display_order)
);
CREATE INDEX idx_trees_species ON trees (species_id);
CREATE INDEX idx_trees_zone ON trees (zone_id);
CREATE TRIGGER trg_trees_updated_at BEFORE UPDATE ON trees
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Planting plans
-- ---------------------------------------------------------------
CREATE TABLE planting_plans (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id           BIGINT NOT NULL REFERENCES zones(id),
    species_id        BIGINT NULL REFERENCES species(id),
    planned_quantity  INTEGER NOT NULL DEFAULT 1,
    target_date       DATE NULL,
    latitude          DECIMAL(10,7) NULL,
    longitude         DECIMAL(10,7) NULL,
    map_pin_x         DECIMAL(5,2) NULL,
    map_pin_y         DECIMAL(5,2) NULL,
    image_path        VARCHAR(255) NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','in_progress','completed','cancelled')),
    notes             TEXT NULL,
    created_by        VARCHAR(150) NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_planting_plans_zone ON planting_plans (zone_id);
CREATE INDEX idx_planting_plans_status ON planting_plans (status);
CREATE TRIGGER trg_planting_plans_updated_at BEFORE UPDATE ON planting_plans
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Visitors (identified by cookie-issued UUID, not login)
-- ---------------------------------------------------------------
CREATE TABLE visitors (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_uuid     CHAR(36) NOT NULL UNIQUE,
    first_seen_at    TIMESTAMP NOT NULL DEFAULT now(),
    last_seen_at     TIMESTAMP NOT NULL DEFAULT now(),
    last_ip_address  VARCHAR(45) NULL,
    last_user_agent  VARCHAR(255) NULL
);
CREATE TRIGGER trg_visitors_last_seen_at BEFORE UPDATE ON visitors
    FOR EACH ROW EXECUTE FUNCTION set_last_seen_at();

-- ---------------------------------------------------------------
-- Tree Scans (one row per scan/view event)
-- ---------------------------------------------------------------
CREATE TABLE tree_scans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id     BIGINT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
    visitor_id  BIGINT NOT NULL REFERENCES visitors(id) ON DELETE CASCADE,
    ip_address  VARCHAR(45) NULL,
    user_agent  VARCHAR(255) NULL,
    scanned_at  TIMESTAMP NOT NULL DEFAULT now(),
    scan_lat           DECIMAL(10,7) NULL,
    scan_lng           DECIMAL(10,7) NULL,
    gps_accuracy_m     DECIMAL(6,2)  NULL,
    gps_available      SMALLINT NOT NULL DEFAULT 0,
    registered_zone_id BIGINT NULL,
    registered_lat     DECIMAL(10,7) NULL,
    registered_lng     DECIMAL(10,7) NULL
);
CREATE INDEX idx_scans_tree_visitor ON tree_scans (tree_id, visitor_id);
CREATE INDEX idx_scans_tree_time ON tree_scans (tree_id, scanned_at);

-- ---------------------------------------------------------------
-- Tree Interests / "Interest Event"
-- ---------------------------------------------------------------
CREATE TABLE tree_interests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id          BIGINT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
    email            VARCHAR(255) NOT NULL,
    activity_type    VARCHAR(20) NOT NULL DEFAULT 'interest_click'
        CHECK (activity_type IN ('interest_click','price_request')),
    contact_channel  VARCHAR(100) NULL,
    lead_status      VARCHAR(20) NOT NULL DEFAULT 'new'
        CHECK (lead_status IN ('new','contacted','converted','closed')),
    lead_updated_at  TIMESTAMP NULL,
    consent_at       TIMESTAMP NULL,
    purge_after      DATE NULL,
    session_hash     CHAR(64) NULL,
    visitor_id    BIGINT NULL REFERENCES visitors(id) ON DELETE SET NULL,
    submitted_at  TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_interests_tree ON tree_interests (tree_id);

-- ---------------------------------------------------------------
-- Observations
-- ---------------------------------------------------------------
CREATE TABLE observations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id        BIGINT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
    observed_at    DATE NOT NULL,
    height_cm      DECIMAL(7,1) NULL,
    canopy_cm      DECIMAL(7,1) NULL,
    health         VARCHAR(10) NOT NULL DEFAULT 'good'
        CHECK (health IN ('good','fair','poor')),
    notes          TEXT NULL,
    recorded_by    VARCHAR(150) NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_observations_tree_date ON observations (tree_id, observed_at);

-- ---------------------------------------------------------------
-- Maintenance Log
-- ---------------------------------------------------------------
CREATE TABLE maintenance_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id        BIGINT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
    activity       VARCHAR(100) NOT NULL,
    performed_at   DATE NOT NULL,
    performed_by   VARCHAR(150) NULL,
    notes          TEXT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_maintenance_tree_date ON maintenance_logs (tree_id, performed_at);

-- ---------------------------------------------------------------
-- Stock sizes — fixed reference data, seeded immediately like install.sql.
-- ---------------------------------------------------------------
CREATE TABLE stock_sizes (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_th        VARCHAR(50) NOT NULL,
    name_en        VARCHAR(50) NULL,
    name_zh        VARCHAR(50) NULL,
    display_order  INTEGER NOT NULL DEFAULT 0
);

INSERT INTO stock_sizes (name_th, name_en, name_zh, display_order) VALUES
('เล็ก', 'Small', '小', 1),
('กลาง', 'Medium', '中', 2),
('ใหญ่', 'Large', '大', 3);

-- ---------------------------------------------------------------
-- Nursery Stock
-- ---------------------------------------------------------------
CREATE TABLE nursery_stock (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id     BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    size_id        INTEGER NULL REFERENCES stock_sizes(id),
    quantity       INTEGER NOT NULL DEFAULT 0,
    price          DECIMAL(10,2) NULL,
    sale_status    VARCHAR(20) NOT NULL DEFAULT 'not_for_sale'
        CHECK (sale_status IN ('available','reserved','sold_out','not_for_sale')),
    sales_channel  VARCHAR(150) NULL,
    updated_at     TIMESTAMP NOT NULL DEFAULT now(),
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_stock_species ON nursery_stock (species_id);
CREATE TRIGGER trg_nursery_stock_updated_at BEFORE UPDATE ON nursery_stock
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Sale transactions
-- ---------------------------------------------------------------
CREATE TABLE sale_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species_id     BIGINT NOT NULL REFERENCES species(id) ON DELETE CASCADE,
    size_id        INTEGER NULL REFERENCES stock_sizes(id),
    quantity       INTEGER NOT NULL DEFAULT 1,
    unit_price     DECIMAL(10,2) NOT NULL,
    total_price    DECIMAL(10,2) NOT NULL,
    interest_id    BIGINT NULL REFERENCES tree_interests(id) ON DELETE SET NULL,
    sold_by        VARCHAR(100) NULL,
    notes          TEXT NULL,
    sold_at        TIMESTAMP NOT NULL DEFAULT now(),
    created_at     TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_sales_species ON sale_transactions (species_id);
CREATE INDEX idx_sales_sold_at ON sale_transactions (sold_at);

-- ---------------------------------------------------------------
-- Plant Location History — append-only move log.
-- ---------------------------------------------------------------
CREATE TABLE plant_location_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id        BIGINT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
    from_zone_id   BIGINT NULL REFERENCES zones(id) ON DELETE SET NULL,
    to_zone_id     BIGINT NULL REFERENCES zones(id) ON DELETE SET NULL,
    from_area_code CHAR(2) NULL,
    to_area_code   CHAR(2) NULL,
    reason         VARCHAR(255) NULL,
    changed_by     BIGINT NULL REFERENCES admins(id) ON DELETE SET NULL,
    changed_at     TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_plh_tree ON plant_location_history (tree_id, changed_at);

-- ---------------------------------------------------------------
-- QR Tags — secondary lookup for printed physical labels.
-- ---------------------------------------------------------------
CREATE TABLE qr_tags (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_code        VARCHAR(30) NOT NULL UNIQUE,
    tree_id         BIGINT NULL REFERENCES trees(id) ON DELETE SET NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'printed'
        CHECK (status IN ('printed','installed','damaged','retired')),
    installed_at    TIMESTAMP NULL,
    last_checked_at TIMESTAMP NULL,
    scan_count      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_qrtags_status ON qr_tags (status, last_checked_at);
CREATE TRIGGER trg_qr_tags_updated_at BEFORE UPDATE ON qr_tags
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Audit Logs — append-only record of admin changes.
-- before_json/after_json kept as TEXT, not JSONB — see conversion notes.
-- ---------------------------------------------------------------
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT NULL REFERENCES admins(id) ON DELETE SET NULL,
    action      VARCHAR(60) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id   BIGINT NOT NULL,
    before_json TEXT NULL,
    after_json  TEXT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id, created_at);
CREATE INDEX idx_audit_admin ON audit_logs (admin_id, created_at);

-- ---------------------------------------------------------------
-- Highlights — daily/scheduled expo event items on the home page.
-- ---------------------------------------------------------------
CREATE TABLE highlights (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    title_en    VARCHAR(200) NULL,
    title_zh    VARCHAR(200) NULL,
    event_date  DATE NOT NULL,
    event_time  VARCHAR(20) NULL,
    zone_id     BIGINT NULL REFERENCES zones(id) ON DELETE SET NULL,
    image_path  VARCHAR(255) NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    is_active   SMALLINT NOT NULL DEFAULT 1,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_highlights_date ON highlights (event_date, is_active);
CREATE TRIGGER trg_highlights_updated_at BEFORE UPDATE ON highlights
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- News Posts
-- ---------------------------------------------------------------
CREATE TABLE news_posts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    title_en     VARCHAR(200) NULL,
    title_zh     VARCHAR(200) NULL,
    excerpt      VARCHAR(500) NULL,
    excerpt_en   VARCHAR(500) NULL,
    excerpt_zh   VARCHAR(500) NULL,
    body         TEXT NULL,
    body_en      TEXT NULL,
    body_zh      TEXT NULL,
    image_path   VARCHAR(255) NULL,
    published_at TIMESTAMP NOT NULL DEFAULT now(),
    is_active    SMALLINT NOT NULL DEFAULT 1,
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_news_published ON news_posts (published_at, is_active);
CREATE TRIGGER trg_news_posts_updated_at BEFORE UPDATE ON news_posts
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Shops / Products — marketplace catalog.
-- ---------------------------------------------------------------
CREATE TABLE shops (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    zone_id      BIGINT NULL REFERENCES zones(id) ON DELETE SET NULL,
    rating       DECIMAL(2,1) NULL,
    review_count INTEGER NOT NULL DEFAULT 0,
    about        TEXT NULL,
    banner_path  VARCHAR(255) NULL,
    is_active    SMALLINT NOT NULL DEFAULT 1,
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_shops_zone ON shops (zone_id, is_active);
CREATE TRIGGER trg_shops_updated_at BEFORE UPDATE ON shops
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE products (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id          BIGINT NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    species_id       BIGINT NULL REFERENCES species(id) ON DELETE SET NULL,
    name             VARCHAR(200) NOT NULL,
    price            DECIMAL(10,2) NOT NULL,
    compare_at_price DECIMAL(10,2) NULL,
    image_path       VARCHAR(255) NULL,
    sold_count       INTEGER NOT NULL DEFAULT 0,
    tag              VARCHAR(50) NULL,
    is_active        SMALLINT NOT NULL DEFAULT 1,
    created_at       TIMESTAMP NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_products_shop ON products (shop_id, is_active);
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Market Interests
-- ---------------------------------------------------------------
CREATE TABLE market_interests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NULL REFERENCES products(id) ON DELETE SET NULL,
    shop_id       BIGINT NULL REFERENCES shops(id) ON DELETE SET NULL,
    email         VARCHAR(255) NOT NULL,
    consent_at    TIMESTAMP NULL,
    purge_after   DATE NULL,
    session_hash  CHAR(64) NULL,
    lead_status   VARCHAR(20) NOT NULL DEFAULT 'new'
        CHECK (lead_status IN ('new','contacted','converted','closed')),
    submitted_at  TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_market_interests_product ON market_interests (product_id);

-- ---------------------------------------------------------------
-- Translation Drafts — pending Gemini-generated EN/ZH text.
-- ---------------------------------------------------------------
CREATE TABLE translation_drafts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(30)  NOT NULL,
    entity_id   BIGINT NOT NULL,
    field_name  VARCHAR(60)  NOT NULL,
    lang        CHAR(2)      NOT NULL,
    source_text TEXT         NOT NULL,
    draft_text  TEXT         NOT NULL,
    source      VARCHAR(20)  NOT NULL DEFAULT 'gemini',
    status      VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','approved','rejected')),
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMP NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX idx_drafts_entity ON translation_drafts (entity_type, entity_id, status);

-- ============================================================================
-- Seed data — the actual dataset running in production as of 2026-09-23
-- (mysqldump of the live database). Inserted in FK-dependency order
-- (roles/categories/zones before the rows that reference them, etc.) and
-- wrapped in one transaction so a failure partway through leaves no
-- half-seeded database behind.
-- ============================================================================
BEGIN;

INSERT INTO settings (setting_key, setting_value, updated_at) VALUES
('default_map_image','assets/uploads/maps/map-siam.png','2026-09-19 15:12:35'),
('default_map_url','https://maps.example.com/park-overview','2026-08-15 17:10:59');

INSERT INTO categories (code, name_th, name_en, name_zh, created_at) VALUES
('001','ไม้ยืนต้น',NULL,NULL,'2026-08-22 14:43:18'),
('002','ไม้พุ่ม',NULL,NULL,'2026-08-22 14:43:25'),
('003','ไม้ล้มลุก',NULL,NULL,'2026-08-22 14:43:32'),
('004','ไม้เลื้อย',NULL,NULL,'2026-08-22 14:43:39'),
('005','ไม้คลุมดิน',NULL,NULL,'2026-08-22 14:43:46'),
('006','ไม้น้ำ',NULL,NULL,'2026-08-22 14:43:51');

INSERT INTO roles (id, role_key, name_th, name_en, description, is_system, created_at) VALUES
(1,'programmer','โปรแกรมเมอร์','Programmer','สิทธิ์สูงสุด เข้าถึงได้ทุกส่วนของระบบ CRUD ทุกอย่าง',1,'2026-08-22 08:28:57'),
(2,'executive','ผู้บริหาร','Executive','ดูแดชบอร์ดและรายงานเพื่อการตัดสินใจ อ่านอย่างเดียว แก้ไข/ลบข้อมูลไม่ได้',1,'2026-08-22 08:28:57'),
(3,'tree_admin','ผู้ดูแลข้อมูลต้นไม้','Tree Admin','จัดการข้อมูลต้นไม้ ชนิดพันธุ์ โซน แหล่งที่มา และ QR Code ประจำวัน',1,'2026-08-22 08:28:57');

INSERT INTO permissions (id, permission_key, module, description) VALUES
(1,'tree.view','tree','ดูรายการ/รายละเอียดต้นไม้ในระบบแอดมิน'),
(2,'tree.create','tree','เพิ่มต้นไม้ใหม่'),
(3,'tree.update','tree','แก้ไขข้อมูลต้นไม้ที่มีอยู่'),
(4,'tree.status.manage','tree','สลับสถานะ Active/Inactive (ใช้แทนการลบถาวร)'),
(5,'tree.image.manage','tree','อัปโหลด/เปลี่ยนรูปต้นไม้'),
(6,'tree.order.manage','tree','จัดลำดับการแสดงผล (Previous/Next)'),
(7,'tree.map.manage','tree','ตั้งค่าแผนที่เฉพาะต้น (ภาพ/ลิงก์)'),
(8,'tree.relationship.manage','tree','จัดการความสัมพันธ์ต้นก่อนหน้า/ถัดไป'),
(9,'tree.location.manage','tree','ย้ายต้นไม้ไปตำแหน่ง/โซน/แหล่งที่มาใหม่'),
(10,'category.manage','master_data','จัดการประเภทพืช'),
(11,'species.manage','master_data','จัดการชนิดพันธุ์พืช'),
(12,'zone.manage','master_data','จัดการโซน/ตำแหน่ง'),
(13,'origin.manage','master_data','จัดการแหล่งที่มาของต้นไม้'),
(14,'qrcode.manage','qr','สร้าง/พิมพ์ QR Code'),
(15,'translation.request','translation','สั่งให้ AI แปลข้อความ'),
(16,'translation.review','translation','ตรวจสอบ/อนุมัติคำแปลของ AI'),
(17,'admin.manage','admin_accounts','จัดการบัญชีผู้ดูแลระบบและบทบาท'),
(18,'gemini.config.manage','admin_accounts','ตั้งค่า Gemini API key/model'),
(19,'scan.view','visitor_data','ดูประวัติ/สถิติการสแกน'),
(20,'visitor.view','visitor_data','ดูข้อมูลผู้เข้าชม (Visitor ID, IP, User-Agent)'),
(21,'interest.view','visitor_data','ดูรายชื่ออีเมลผู้สนใจ'),
(22,'interest.manage','visitor_data','อัปเดตสถานะการติดตามผู้สนใจ (Lead)'),
(23,'dashboard.view','reporting','เข้าถึงแดชบอร์ดผู้บริหาร'),
(24,'stats.tree.view','reporting','สถิติรายต้น'),
(25,'stats.category.view','reporting','สถิติรายประเภทพืช'),
(26,'stats.zone.view','reporting','สถิติรายโซน'),
(27,'trends.view','reporting','แนวโน้มผู้เข้าชม/การสแกนตามช่วงเวลา'),
(28,'revenue.view','reporting','ข้อมูลราคา/ยอดขาย (ถ้ามี)'),
(29,'reports.export','reporting','ส่งออกรายงานเป็น CSV'),
(30,'map.settings.manage','system','ตั้งค่าแผนที่เริ่มต้นของทั้งระบบ'),
(31,'settings.manage','system','ตั้งค่าระดับระบบ (โลโก้ ฯลฯ)'),
(32,'plan.manage','master_data','จัดการแผนการปลูกต้นไม้ล่วงหน้า');

INSERT INTO role_permissions (role_id, permission_id) VALUES
(1,1),(1,2),(1,3),(1,4),(1,5),(1,6),(1,7),(1,8),(1,9),(1,10),(1,11),(1,12),(1,13),(1,14),(1,15),(1,16),
(1,17),(1,18),(1,19),(1,20),(1,21),(1,22),(1,23),(1,24),(1,25),(1,26),(1,27),(1,28),(1,29),(1,30),(1,31),(1,32),
(2,19),(2,20),(2,21),(2,23),(2,24),(2,25),(2,26),(2,27),(2,28),(2,29),
(3,1),(3,2),(3,3),(3,4),(3,5),(3,6),(3,7),(3,8),(3,9),(3,10),(3,11),(3,12),(3,13),(3,14),(3,15),(3,16),(3,19),(3,24),(3,32);

INSERT INTO admins (id, username, password_hash, role_id, failed_login_attempts, locked_until, created_at) VALUES
(1,'admin','$2y$12$cm9oXThdYnPgXPMAagOkkOflGT1pRmmrTdzhgCxJtJXHZ9zMQM8ba',1,0,NULL,'2026-08-15 17:10:59'),
(2,'exec_test','$2y$12$FkjsfO/FJ1R70acWrLCjiuqsH5hov4s8Ek/ZE6OM6lRENmfOyqCke',2,0,NULL,'2026-08-22 08:48:26'),
(3,'tree_admin_test','$2y$12$FkjsfO/FJ1R70acWrLCjiuqsH5hov4s8Ek/ZE6OM6lRENmfOyqCke',3,0,NULL,'2026-08-22 08:48:26');

INSERT INTO zones (id, zone_code, zone_number, name, name_en, name_zh, description, description_en, description_zh, created_at, updated_at, map_pin_x, map_pin_y) VALUES
(1,'Z1','001','โซนสวนหน้า','Front Garden Zone','前花园区','พื้นที่จัดแสดงหลักใกล้ทางเข้า','Main display area near the entrance.','入口附近的主要展示区。','2026-08-15 17:10:59','2026-08-15 17:10:59',NULL,NULL),
(2,'Z2','002','โซน 2','Zone 2','区域2',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-09-19 15:13:30',NULL,NULL),
(3,'Z3','003','โซน 3','Zone 3','区域3',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(4,'Z4','004','โซน 4','Zone 4','区域4',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(5,'Z5','005','โซน 5','Zone 5','区域5',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(6,'Z6','006','โซน 6','Zone 6','区域6',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(7,'Z7','007','โซน 7','Zone 7','区域7',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(8,'Z8','008','โซน 8','Zone 8','区域8',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(9,'Z9','009','โซน 9','Zone 9','区域9',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-08-15 17:12:31',NULL,NULL),
(10,'Z10','010','โซน 10','Zone 10','区域10',NULL,NULL,NULL,'2026-08-15 17:12:31','2026-09-19 15:15:03',NULL,NULL);

INSERT INTO subtypes (id, category_code, name_th, name_en, name_zh, created_at) VALUES
(4,'001','ไม้ผล',NULL,NULL,'2026-08-22 17:58:30'),
(5,'004','ไม้ดอก',NULL,NULL,'2026-08-22 17:58:40'),
(6,NULL,'ไม้ประดับ',NULL,NULL,'2026-08-22 17:58:45'),
(7,NULL,'ไม้ให้ร่มเงา',NULL,NULL,'2026-08-22 17:58:50'),
(8,NULL,'ไม้เศรษฐกิจ',NULL,NULL,'2026-08-22 17:58:56'),
(9,NULL,'ไม้ป่า',NULL,NULL,'2026-08-22 17:59:28'),
(13,NULL,'ไม้ยืนต้น',NULL,NULL,'2026-08-22 18:12:26'),
(14,NULL,'ไม้มงคล',NULL,NULL,'2026-08-22 18:13:37'),
(15,NULL,'ไม้หอม',NULL,NULL,'2026-08-22 18:14:15'),
(16,NULL,'ไม้สมุนไพร',NULL,NULL,'2026-08-22 18:14:39'),
(17,'001','ปาล์ม',NULL,NULL,'2026-08-22 18:15:03'),
(18,NULL,'ไผ่',NULL,NULL,'2026-08-22 18:15:08'),
(19,NULL,'ไทรและไม้ในกลุ่มไทร',NULL,NULL,'2026-08-22 18:15:14'),
(20,'004','สน',NULL,NULL,'2026-08-22 18:15:20'),
(21,NULL,'ไม้พรรณท้องถิ่น',NULL,NULL,'2026-08-22 18:15:26');

INSERT INTO species (id, category_code, subtype_id, species_code, classification_id, name, name_en, name_zh, name_common, name_scientific, image_path, description, description_en, description_zh, care_instructions, care_instructions_en, care_instructions_zh, characteristics, characteristics_en, characteristics_zh, properties, properties_en, properties_zh, benefits, benefits_en, benefits_zh, cautions, cautions_en, cautions_zh, part_uses, part_uses_en, part_uses_zh, created_at, updated_at) VALUES
(93,'001',17,'001',NULL,'ปาล์มฤาษี',NULL,NULL,'ปาล์มเคราฤาษี','Coccothrinax crinita','assets/uploads/species/948869082004588ee18291b78a795110.jpg','ปาล์มเคราฤาษี เป็นปาล์มประดับชนิดหนึ่งที่มีความแปลกตาและหาได้ค่อนข้างยาก โตช้ามาก มีลักษณะเด่นที่เห็นได้ชัดเจนคือเส้นใยสีน้ำตาลอ่อนคลุมลำต้นจนดูเหมือนหนวดเคราของคนแก่ จัดเป็นพืชที่เลี้ยงง่าย ทนทาน และมีมูลค่าสูงในตลาดไม้ประดับ',NULL,NULL,'แสงแดด: ชอบแสงแดดจัด แดดรำไรถึงแดดเต็มวัน (ตากแดด 100% ได้)การให้น้ำ: ปานกลาง รดน้ำวันละ 1 ครั้ง หรือ 2-3 วันครั้งเมื่อดินแห้ง ระวังอย่าให้ดินแฉะขังเพราะจะทำให้รากเน่าดินที่ใช้ปลูก: ดินร่วนผสมทรายเน้น ระบายน้ำได้ดีมากการใส่ปุ๋ย: ปุ๋ยคอกหรือปุ๋ยละลายช้า (เช่น ออสโมโค้ท) สูตรเสมอ ทุกๆ 3 เดือน',NULL,NULL,'ลำต้น: ลำต้นเดี่ยว ตั้งตรง สูงได้เต็มที่ประมาณ 6-10 เมตร เส้นผ่านศูนย์กลางลำต้นประมาณ 15-20 เซนติเมตรเส้นใย (เครา): เส้นใยหนาสีน้ำตาลปนเทา หุ้มรอบลำต้นตั้งแต่โคนจรดสัปปะรด (ส่วนยอด) เส้นใยมีความยาวและฟูใบ: ใบเดี่ยวรูปพัด (Fan palm) แผ่นใบกลม ขนาดใหญ่ กว้าง 1-1.5 เมตร ใบสีเขียวเข้ม ใต้ใบมีสีนวลเงินดอก: ออกเป็นช่อระหว่างกาบใบ ดอกมีขนาดเล็กสีเหลืองครีมผล: ผลกลม ขนาดเล็ก ประมาณ 1-2 เซนติเมตร เมื่อสุกจะเป็นสีม่วงเข้มหรือสีดำ',NULL,NULL,'ความทนทานสูง: ทนต่อสภาพอากาศร้อนแห้งแล้งได้ดีเยี่ยม และทนลมแรงได้ดีเจริญเติบโตช้า: ทำให้คงรูปทรงเดิมได้นาน ไม่โตเร็วจนล้นพื้นที่จัดสวนความเหนียวของเส้นใย: เส้นใยรอบลำต้นมีความเหนียว ทนทานต่อการเปื่อยยุ่ยจากน้ำฝน',NULL,NULL,'ไม้ประดับจัดสวน: นิยมปลูกเป็น ไม้ประธาน ในการจัดสวนหย่อม สวนสไตล์โมเดิร์น หรือสวนหิน เพื่อสร้างจุดดึงดูดสายตาเพิ่มมูลค่าให้สถานที่: เนื่องจากเป็นไม้โตช้าและหายาก การนำมาประดับโรงแรม รีสอร์ต หรือบ้านพักอาศัย จะช่วยเพิ่มความหรูหราและมีเอกลักษณ์พรางแสงและดักฝุ่น: พุ่มใบที่แน่นและเส้นใยรอบลำต้นช่วยกรองแสงแดดสะท้อนและดักจับฝุ่นละอองในอากาศได้เล็กน้อย',NULL,NULL,'เสี่ยงต่ออัคคีภัย: เส้นใยฝอยที่ปกคลุมลำต้นมีลักษณะแห้งเมื่อโดนแดดจัด ติดไฟได้ง่ายและรวดเร็วมาก ควรหลีกเลี่ยงการปลูกใกล้จุดสูบบุหรี่ เตาปิ้งย่าง หรือบริเวณที่มีการเผาขยะแหล่งสะสมของสัตว์เล็ก: เส้นใยที่หนาทึบอาจกลายเป็นที่หลบซ่อนของแมลง แมงมุม หรือสัตว์เลื้อยคลานขนาดเล็กได้ หากไม่ได้ดูแลรักษาความสะอาดผู้ที่เป็นภูมิแพ้รุนแรง: เส้นใยอาจมีฝุ่นละอองหรือละอองเกสรติดอยู่ได้ง่าย ผู้ที่มีอาการภูมิแพ้ฝุ่นละอองควรสวมหน้ากากขณะตัดแต่งกิ่งก้าน',NULL,NULL,'ลำต้น: ในถิ่นกำเนิด (คิวบา) เนื้อไม้ที่มีความแข็งมักถูกนำมาใช้ทำเสาบ้านเรือนขนาดเล็กหรือรั้วเส้นใยรอบลำต้น (เครา): ในอดีตชาวพื้นเมืองนำมาใช้เป็น วัสดุยัดไส้หมอนและเบาะนั่ง เพราะมีความนุ่มและยืดหยุ่นคล้ายนุ่น รวมถึงนำมาถักทอเป็นเชือกใบ: นำมาใช้มุงหลังคาเพิงชั่วคราว หรือนำมาจักสานทำหมวกและตะกร้าผล: เป็นอาหารของนกและสัตว์ป่าในธรรมชาติ ช่วยในการขยายพันธุ์พืชหากคุณกำลังวางแผนปลูก สามารถบอกเพิ่มเติมได้นะครับว่า:ต้องการปลูก ลงดินกลางแจ้ง หรือ ใส่กระถางอยากทราบ ราคาประเมินในตลาด ปัจจุบันหรือไม่',NULL,NULL,'2026-09-22 17:20:41','2026-09-22 17:20:41');

INSERT INTO trees (id, slug, species_id, zone_id, area_code, plant_code, plant_code_updated_at, label, status, data_status, image_path, map_image_path, map_url, qr_code_path, latitude, longitude, location_updated_at, display_order, is_active, created_at, updated_at, map_pin_x, map_pin_y) VALUES
(93,NULL,93,5,'01','001001005010001','2026-09-22 17:20:41',NULL,'healthy','published','assets/uploads/tree/ccb499dfb076fbb416b4b6254c5c6b72.jpg',NULL,NULL,'assets/uploads/qr/tree-93.png',NULL,NULL,NULL,1,1,'2026-09-22 17:20:41','2026-09-22 17:20:41',NULL,NULL),
(94,NULL,93,5,'01','001001005010002','2026-09-22 17:20:41',NULL,'healthy','published','assets/uploads/tree/ccb499dfb076fbb416b4b6254c5c6b72.jpg',NULL,NULL,'assets/uploads/qr/tree-94.png',NULL,NULL,NULL,2,1,'2026-09-22 17:20:41','2026-09-22 17:20:41',NULL,NULL),
(95,NULL,93,5,'01','001001005010003','2026-09-22 17:20:41',NULL,'healthy','published','assets/uploads/tree/ccb499dfb076fbb416b4b6254c5c6b72.jpg',NULL,NULL,'assets/uploads/qr/tree-95.png',NULL,NULL,NULL,3,1,'2026-09-22 17:20:41','2026-09-22 17:20:41',NULL,NULL);

INSERT INTO visitors (id, visitor_uuid, first_seen_at, last_seen_at, last_ip_address, last_user_agent) VALUES
(17,'b88de6a0-6b53-48eb-8469-5fb0987d2581','2026-09-19 15:23:49','2026-09-19 15:23:49','::1','Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.26100.9444'),
(18,'070a31b7-773c-438e-bf18-0db113134645','2026-09-19 15:23:49','2026-09-19 15:23:49','::1','Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.26100.9444'),
(19,'0e74cbf9-360c-4a9a-8e30-71864230d28f','2026-09-19 15:24:30','2026-09-19 15:24:30','::1','Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) WindowsPowerShell/5.1.26100.9444'),
(20,'2bdbbd2b-71f7-4d9e-93ff-871585244735','2026-09-19 15:36:16','2026-09-19 15:36:16','127.0.0.1',''),
(21,'b9b7236e-4140-496d-8176-5d7078f4adc4','2026-09-19 15:36:16','2026-09-19 15:36:16','127.0.0.1',''),
(22,'6e0e254e-50bb-41c1-b4c7-33353613bb65','2026-09-19 15:40:33','2026-09-19 15:40:33','127.0.0.1',''),
(23,'5c63c673-f1a0-46ed-bed2-1ccf8c9c6368','2026-09-19 15:40:33','2026-09-19 15:40:33','127.0.0.1',''),
(24,'07b36cbc-cf7e-425a-a4cf-b22fe82a3399','2026-09-19 15:40:56','2026-09-19 15:40:56','127.0.0.1',''),
(25,'6a3727c4-e034-4713-8351-00e1a335242a','2026-09-19 15:40:56','2026-09-19 15:40:56','127.0.0.1',''),
(26,'09a3f2cc-5bb8-44a9-947b-e0e602c70502','2026-09-19 15:55:05','2026-09-19 15:55:05','127.0.0.1',''),
(27,'844c2366-6076-4110-b85f-d6316d67fb8e','2026-09-19 15:55:05','2026-09-19 15:55:05','127.0.0.1',''),
(28,'453bb97f-918b-4ca1-a832-59ef9bb6bd02','2026-09-19 16:02:12','2026-09-19 16:02:12','127.0.0.1',''),
(29,'617a4336-c847-40ff-bdb9-be694c693ddb','2026-09-19 16:02:12','2026-09-19 16:02:12','127.0.0.1',''),
(30,'231adab9-088c-4719-af59-c88bdbebf379','2026-09-19 16:02:43','2026-09-19 16:02:43','127.0.0.1',''),
(31,'eb07aae1-40ec-4684-9a6d-e82c5488c946','2026-09-19 16:02:44','2026-09-19 16:02:44','127.0.0.1',''),
(32,'9439cbc9-adf6-4516-9353-161edcc6f4ea','2026-09-19 16:14:42','2026-09-19 16:14:42','::1','Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Mobile Safari/537.36'),
(33,'fa10d04d-4555-4c81-ab08-df5d687d4e89','2026-09-22 16:35:18','2026-09-22 16:35:18','::1','curl/8.21.0'),
(34,'49631469-86a1-480a-a53e-e3b9ae723571','2026-09-22 16:36:29','2026-09-22 17:21:24','::1','Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Mobile Safari/537.36');

-- Only one live tree_scans row survives the port: the rest (ids 21-38)
-- reference tree ids (45,47,48,50,52,...) that belonged to trees which have
-- since been deleted from the live database — trees.id in this schema is a
-- real FK with ON DELETE CASCADE (see CREATE TABLE tree_scans above), so a
-- scan row for a tree that no longer exists cannot be reinserted, and
-- historically was likely cascade-deleted already once that tree was
-- removed on the MySQL side too (mysqldump's --no-create-info dump only
-- reflects whatever FK behavior actually already happened there). Dropped
-- rather than carried forward as dead weight.
INSERT INTO tree_scans (id, tree_id, visitor_id, ip_address, user_agent, scanned_at, scan_lat, scan_lng, gps_accuracy_m, gps_available, registered_zone_id, registered_lat, registered_lng) VALUES
(39,93,34,'::1','Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Mobile Safari/537.36','2026-09-22 17:21:22',13.7196665,100.4530332,14.52,1,5,NULL,NULL);

COMMIT;

-- ---------------------------------------------------------------
-- Advance every identity sequence past the explicit ids inserted above, so
-- the next INSERT from the app (which never specifies an id) doesn't
-- collide with one of these seed rows.
-- ---------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('roles','id'), (SELECT COALESCE(MAX(id), 1) FROM roles));
SELECT setval(pg_get_serial_sequence('permissions','id'), (SELECT COALESCE(MAX(id), 1) FROM permissions));
SELECT setval(pg_get_serial_sequence('admins','id'), (SELECT COALESCE(MAX(id), 1) FROM admins));
SELECT setval(pg_get_serial_sequence('subtypes','id'), (SELECT COALESCE(MAX(id), 1) FROM subtypes));
SELECT setval(pg_get_serial_sequence('zones','id'), (SELECT COALESCE(MAX(id), 1) FROM zones));
SELECT setval(pg_get_serial_sequence('species','id'), (SELECT COALESCE(MAX(id), 1) FROM species));
SELECT setval(pg_get_serial_sequence('trees','id'), (SELECT COALESCE(MAX(id), 1) FROM trees));
SELECT setval(pg_get_serial_sequence('visitors','id'), (SELECT COALESCE(MAX(id), 1) FROM visitors));
SELECT setval(pg_get_serial_sequence('tree_scans','id'), (SELECT COALESCE(MAX(id), 1) FROM tree_scans));
SELECT setval(pg_get_serial_sequence('stock_sizes','id'), (SELECT COALESCE(MAX(id), 1) FROM stock_sizes));
